package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("UI tests of livexp app")
    void generatedTest() {
        step("Open https://livexp.com/ru", () -> {
            step("// todo: just add selenium action");
        });

        step("Click 'Все языки' button", () -> {
            step("// todo: just add selenium action");
        });

        step("Set 'Английский' in the search field", () -> {
            step("// todo: just add selenium action");
        });

        step("Verify results", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://livexp.com/ru'", () ->
            open("https://livexp.com/ru"));

        step("Page title should have text 'LiveXP: Изучайте языки онлайн с Лучшими Преподавателями'", () -> {
            String expectedTitle = "LiveXP: Изучайте языки онлайн с Лучшими Преподавателями";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://livexp.com/ru'", () ->
            open("https://livexp.com/ru"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}